version: 19
permalink: pretty

port: 4001

exclude:
  - README.md
  - gulpfile.js
  - package.json
  - .editorconfig
  - .gitignore
  - tmp
  - node_modules
  - css/*.css
  - js/*.js

kramdown:
  input: GFM

defaults:
  -
    scope:
      path: ""
    values:
      layout: main
